-- Generated by npm run erd:sync from the application SQLite schema.

-- Use src/db.ts for versioned migration of existing databases.

PRAGMA foreign_keys = ON;

BEGIN;

CREATE TABLE activity_logs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER,
      action TEXT NOT NULL,
      entity_type TEXT,
      entity_id INTEGER,
      details TEXT,
      ip_address TEXT,
      user_agent TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
    );

CREATE TABLE appointment_status_history (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      appointment_id INTEGER NOT NULL,
      old_status TEXT,
      new_status TEXT NOT NULL,
      changed_by_user_id INTEGER,
      note TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
      FOREIGN KEY (changed_by_user_id) REFERENCES users (id) ON DELETE SET NULL
    );

CREATE TABLE appointments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      booking_code TEXT NOT NULL UNIQUE,
      patient_id INTEGER NOT NULL,
      doctor_id INTEGER NOT NULL,
      specialty_id INTEGER,
      service_id INTEGER,
      appointment_date TEXT NOT NULL,
      start_time TEXT NOT NULL,
      end_time TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'pending',
      symptoms TEXT,
      notes TEXT,
      cancellation_reason TEXT,
      source TEXT NOT NULL DEFAULT 'online',
      priority_level TEXT NOT NULL DEFAULT 'online',
      priority_reason TEXT,
      is_bumped INTEGER DEFAULT 0,
      bumped_from_slot TEXT,
      estimated_start_time TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
      FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
      FOREIGN KEY (specialty_id) REFERENCES specialties (id) ON DELETE SET NULL,
      FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE SET NULL
    );

CREATE TABLE articles (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      category TEXT NOT NULL, /* 'thuoc', 'duoc-lieu', 'benh', 'co-the' */
      category_name TEXT NOT NULL,
      pill_label TEXT NOT NULL,
      icon TEXT DEFAULT '💊',
      slug TEXT NOT NULL UNIQUE,
      title TEXT NOT NULL,
      summary TEXT NOT NULL,
      content TEXT NOT NULL,
      author_name TEXT NOT NULL,
      author_role TEXT NOT NULL,
      views_count INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'active',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE beds (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      room_id INTEGER NOT NULL,
      bed_number TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'available',
      current_patient_id INTEGER,
      current_medical_record_id INTEGER,
      current_doctor_id INTEGER,
      admission_date DATETIME,
      notes TEXT,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(room_id, bed_number),
      FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
      FOREIGN KEY (current_patient_id) REFERENCES patients (id) ON DELETE SET NULL,
      FOREIGN KEY (current_medical_record_id) REFERENCES medical_records (id) ON DELETE SET NULL,
      FOREIGN KEY (current_doctor_id) REFERENCES doctors (id) ON DELETE SET NULL
    );

CREATE TABLE contact_requests (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      name TEXT NOT NULL,
      phone TEXT NOT NULL,
      email TEXT NOT NULL,
      subject TEXT,
      message TEXT NOT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE doctor_leaves (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      doctor_id INTEGER NOT NULL,
      start_date TEXT NOT NULL,
      end_date TEXT NOT NULL,
      reason TEXT,
      status TEXT NOT NULL DEFAULT 'approved',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE
    );

CREATE TABLE doctor_schedules (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      doctor_id INTEGER NOT NULL,
      day_of_week INTEGER NOT NULL,
      start_time TEXT NOT NULL,
      end_time TEXT NOT NULL,
      max_patients INTEGER DEFAULT 20,
      is_active INTEGER DEFAULT 1,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, slot_duration INTEGER DEFAULT 30, status TEXT DEFAULT 'active',
      FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE
    );

CREATE TABLE doctor_specialties (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      doctor_id INTEGER NOT NULL,
      specialty_id INTEGER NOT NULL,
      is_primary INTEGER DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(doctor_id, specialty_id),
      FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
      FOREIGN KEY (specialty_id) REFERENCES specialties (id) ON DELETE CASCADE
    );

CREATE TABLE doctors (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL UNIQUE,
      title TEXT NOT NULL DEFAULT 'Bác sĩ',
      bio TEXT,
      experience_years INTEGER DEFAULT 1,
      consultation_fee REAL NOT NULL DEFAULT 0.00,
      rating REAL NOT NULL DEFAULT 0.00,
      rating_count INTEGER NOT NULL DEFAULT 0,
      room_number TEXT NOT NULL DEFAULT '',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE TABLE examination_queues (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      appointment_id INTEGER NOT NULL UNIQUE,
      queue_number TEXT NOT NULL,
      queue_date TEXT,
      room TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'waiting',
      priority_level TEXT NOT NULL DEFAULT 'online',
      priority_order INTEGER NOT NULL DEFAULT 3,
      is_bumped INTEGER DEFAULT 0,
      bumped_reason TEXT,
      checkin_time DATETIME DEFAULT CURRENT_TIMESTAMP,
      called_time DATETIME,
      finish_time DATETIME,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE
    );

CREATE TABLE favorite_doctors (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      patient_id INTEGER NOT NULL,
      doctor_id INTEGER NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(patient_id, doctor_id),
      FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
      FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE
    );

CREATE TABLE medical_records (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      appointment_id INTEGER NOT NULL UNIQUE,
      patient_id INTEGER NOT NULL,
      doctor_id INTEGER NOT NULL,
      parent_visit_id INTEGER,
      visit_type TEXT NOT NULL DEFAULT 'initial',
      treatment_type TEXT NOT NULL DEFAULT 'outpatient',
      inpatient_room TEXT,
      inpatient_bed TEXT,
      admission_date TEXT,
      discharge_date TEXT,
      vital_signs TEXT,
      anamnesis TEXT,
      clinical_diagnosis TEXT NOT NULL,
      icd10_code TEXT,
      treatment_plan TEXT,
      doctor_notes TEXT,
      re_examination_date TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, bed_id INTEGER REFERENCES beds (id),
      FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
      FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
      FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
      FOREIGN KEY (parent_visit_id) REFERENCES medical_records (id)
    );

CREATE TABLE medicines (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      code TEXT,
      name TEXT NOT NULL,
      unit TEXT NOT NULL DEFAULT 'Viên',
      usage_instruction TEXT,
      unit_price REAL NOT NULL DEFAULT 0.00,
      stock_quantity INTEGER NOT NULL DEFAULT 100,
      status TEXT NOT NULL DEFAULT 'active',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    , category TEXT);

CREATE TABLE notifications (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      title TEXT NOT NULL,
      message TEXT NOT NULL,
      type TEXT DEFAULT 'general',
      link TEXT,
      is_read INTEGER DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE TABLE patients (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL UNIQUE,
      dob TEXT,
      gender TEXT DEFAULT 'other',
      blood_group TEXT,
      address TEXT,
      emergency_contact TEXT,
      health_insurance_no TEXT,
      medical_history TEXT,
      priority_category TEXT DEFAULT 'normal',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE TABLE payments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      appointment_id INTEGER NOT NULL UNIQUE,
      invoice_code TEXT NOT NULL UNIQUE,
      service_fee REAL NOT NULL DEFAULT 0.00,
      medicine_fee REAL NOT NULL DEFAULT 0.00,
      discount REAL NOT NULL DEFAULT 0.00,
      total_amount REAL NOT NULL DEFAULT 0.00,
      final_amount REAL NOT NULL DEFAULT 0.00,
      payment_method TEXT NOT NULL DEFAULT 'cash',
      payment_status TEXT NOT NULL DEFAULT 'unpaid',
      paid_at DATETIME,
      cashier_user_id INTEGER,
      notes TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, note TEXT,
      FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
      FOREIGN KEY (cashier_user_id) REFERENCES users (id) ON DELETE SET NULL
    );

CREATE TABLE prescription_items (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      prescription_id INTEGER NOT NULL,
      medicine_id INTEGER,
      medicine_name TEXT NOT NULL,
      dosage TEXT,
      unit TEXT DEFAULT 'Viên',
      quantity REAL NOT NULL DEFAULT 1,
      morning TEXT DEFAULT '0',
      noon TEXT DEFAULT '0',
      afternoon TEXT DEFAULT '0',
      night TEXT DEFAULT '0',
      instructions TEXT,
      unit_price REAL NOT NULL DEFAULT 0.00,
      amount REAL NOT NULL DEFAULT 0.00,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (prescription_id) REFERENCES prescriptions (id) ON DELETE CASCADE,
      FOREIGN KEY (medicine_id) REFERENCES medicines (id) ON DELETE SET NULL
    );

CREATE TABLE prescriptions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      medical_record_id INTEGER NOT NULL UNIQUE,
      appointment_id INTEGER,
      doctor_id INTEGER,
      patient_id INTEGER,
      total_amount REAL NOT NULL DEFAULT 0.00,
      usage_instructions TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (medical_record_id) REFERENCES medical_records (id) ON DELETE CASCADE,
      FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
      FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
      FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
    );

CREATE TABLE receptionists (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL UNIQUE,
      staff_code TEXT NOT NULL UNIQUE,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, department TEXT DEFAULT 'Bộ phận Tiếp đón & Thu ngân', shift_default TEXT DEFAULT 'Sáng - Chiều',
      FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE TABLE reviews (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      patient_id INTEGER NOT NULL,
      doctor_id INTEGER NOT NULL,
      appointment_id INTEGER UNIQUE,
      rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
      comment TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP, is_anonymous INTEGER DEFAULT 0,
      FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
      FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
      FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE SET NULL
    );

CREATE TABLE roles (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      code TEXT NOT NULL UNIQUE,
      name TEXT NOT NULL,
      description TEXT
    );

CREATE TABLE rooms (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      room_number TEXT UNIQUE NOT NULL,
      room_name TEXT NOT NULL,
      department_name TEXT DEFAULT 'Khoa Nội',
      room_type TEXT DEFAULT 'inpatient',
      total_beds INTEGER DEFAULT 4,
      status TEXT DEFAULT 'active',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE services (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      specialty_id INTEGER,
      name TEXT NOT NULL,
      description TEXT,
      price REAL NOT NULL,
      duration_minutes INTEGER DEFAULT 30,
      status TEXT NOT NULL DEFAULT 'active',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (specialty_id) REFERENCES specialties (id) ON DELETE SET NULL
    );

CREATE TABLE specialties (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      slug TEXT NOT NULL UNIQUE,
      description TEXT,
      icon TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    , image TEXT, status TEXT NOT NULL DEFAULT 'active');

CREATE TABLE user_roles (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      role TEXT NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id, role),
      FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE TABLE users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      role TEXT NOT NULL DEFAULT 'patient',
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      phone TEXT,
      avatar TEXT,
      status TEXT NOT NULL DEFAULT 'active',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );

CREATE INDEX idx_activity_logs_user ON activity_logs (user_id);

CREATE INDEX idx_appointments_doc_date ON appointments (doctor_id, appointment_date);

CREATE INDEX idx_appointments_patient ON appointments (patient_id);

CREATE INDEX idx_appointments_status ON appointments (status);

CREATE INDEX idx_beds_patient ON beds (current_patient_id);

CREATE INDEX idx_beds_room_status ON beds (room_id, status);

CREATE INDEX idx_contact_requests_created ON contact_requests(created_at);

CREATE INDEX idx_payments_status ON payments (payment_status);

CREATE INDEX idx_prescription_items_pres ON prescription_items (prescription_id);

CREATE INDEX idx_prescriptions_record ON prescriptions (medical_record_id);

CREATE INDEX idx_queue_room_status ON examination_queues (room, status);

CREATE INDEX idx_user_roles_user ON user_roles (user_id);

CREATE UNIQUE INDEX uq_appointment_doctor_slot ON appointments(doctor_id, appointment_date, start_time) WHERE status NOT IN ('cancelled');

CREATE UNIQUE INDEX uq_doctor_specialties_pair ON doctor_specialties(doctor_id, specialty_id);

CREATE UNIQUE INDEX uq_medicines_code ON medicines(code);

CREATE UNIQUE INDEX uq_prescriptions_medical_record ON prescriptions(medical_record_id);

CREATE UNIQUE INDEX uq_queue_date_room_number ON examination_queues(queue_date, room, queue_number)
          WHERE queue_date IS NOT NULL;

CREATE UNIQUE INDEX uq_specialties_name ON specialties(name);

COMMIT;
