/** Generate and verify the schema documentation from a fresh application SQLite DB. */
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');

const root = path.resolve(__dirname, '..');
const dbPath = path.join(os.tmpdir(), `medibook-erd-${process.pid}-${crypto.randomBytes(4).toString('hex')}.sqlite`);
process.env.DATABASE_PATH = dbPath;
process.env.NODE_ENV = 'production';

let db;
try {
  db = require(path.join(root, 'dist', 'db'));
  const tables = db.prepare("SELECT name, sql FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();
  const indexes = db.prepare("SELECT name, sql FROM sqlite_master WHERE type = 'index' AND sql IS NOT NULL ORDER BY name").all();
  const info = tables.map(table => {
    const columns = db.pragma(`table_info(${table.name})`);
    const foreignKeys = db.pragma(`foreign_key_list(${table.name})`);
    const uniqueColumns = db.pragma(`index_list(${table.name})`)
      .filter(index => index.unique && !index.partial)
      .map(index => db.pragma(`index_info(${index.name})`).map(column => column.name));
    return { ...table, columns, foreignKeys, uniqueColumns };
  });
  if (db.pragma('integrity_check', { simple: true }) !== 'ok' || db.pragma('foreign_key_check').length) {
    throw new Error('Fresh SQLite database failed integrity checks');
  }

  const relationship = [];
  for (const table of info) {
    for (const fk of table.foreignKeys) {
      const unique = table.uniqueColumns.some(cols => cols.length === 1 && cols[0] === fk.from)
        || table.columns.some(col => col.name === fk.from && col.pk);
      relationship.push({ child: table.name, parent: fk.table, from: fk.from, to: fk.to,
        cardinality: unique ? 'o|' : 'o{' });
    }
  }
  relationship.sort((a, b) => `${a.parent}.${a.child}.${a.from}`.localeCompare(`${b.parent}.${b.child}.${b.from}`));

  const sql = [
    '-- Generated by npm run erd:sync from the application SQLite schema.',
    '-- Use src/db.ts for versioned migration of existing databases.',
    'PRAGMA foreign_keys = ON;',
    'BEGIN;',
    ...tables.map(table => `${table.sql};`),
    ...indexes.map(index => `${index.sql};`),
    'COMMIT;'
  ].join('\n\n') + '\n';

  // Prove the published SQL can create the same SQLite structure by itself.
  const Database = require('better-sqlite3');
  const reconstructed = new Database(':memory:');
  try {
    reconstructed.exec(sql);
    const recreatedTables = reconstructed.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map(row => row.name);
    const originalTables = tables.map(table => table.name);
    if (JSON.stringify(recreatedTables) !== JSON.stringify(originalTables)) throw new Error('Standalone schema table list differs from app DB');
    for (const table of info) {
      const columns = reconstructed.pragma(`table_info(${table.name})`);
      const foreignKeys = reconstructed.pragma(`foreign_key_list(${table.name})`);
      if (JSON.stringify(columns) !== JSON.stringify(table.columns) ||
          JSON.stringify(foreignKeys) !== JSON.stringify(table.foreignKeys))
        throw new Error(`Standalone schema differs for table ${table.name}`);
    }
    if (reconstructed.pragma('integrity_check', { simple: true }) !== 'ok' || reconstructed.pragma('foreign_key_check').length)
      throw new Error('Standalone schema failed SQLite integrity checks');
  } finally { reconstructed.close(); }

  const markdown = [
    '# MediBook — ERD theo SQLite đang chạy',
    '',
    `Tự sinh bằng \`npm run erd:sync\` từ DB mới tạo bởi \`src/db.ts\`. Schema hiện có **${tables.length} bảng** và **${relationship.length} khóa ngoại**. ` +
      'Các bảng, cột và quan hệ dưới đây phản ánh code chạy thật; `contact_requests` là bảng phát sinh sau ERD cũ.',
    '',
    '```mermaid',
    'erDiagram',
    ...relationship.map(rel => `    ${rel.parent} ||--${rel.cardinality} ${rel.child} : "${rel.from}"`),
    '```',
    '',
    '## Bảng và cột',
    '',
    ...info.flatMap(table => [
      `### ${table.name}`,
      '',
      '| Cột | Kiểu | Ràng buộc |',
      '|---|---|---|',
      ...table.columns.map(col => {
        const fk = table.foreignKeys.find(item => item.from === col.name);
        const flags = [col.pk ? 'PK' : '', col.notnull ? 'NOT NULL' : '',
          table.uniqueColumns.some(cols => cols.length === 1 && cols[0] === col.name) ? 'UNIQUE' : '',
          fk ? `FK → ${fk.table}.${fk.to}; DELETE ${fk.on_delete}` : ''].filter(Boolean);
        return `| ${col.name} | ${col.type || 'ANY'} | ${flags.join('; ') || '—'} |`;
      }),
      ''
    ]),
    '## Giới hạn',
    '',
    '- Các mối quan hệ suy ra từ `PRAGMA foreign_key_list`; liên hệ nghiệp vụ không có FK sẽ không xuất hiện.',
    '- `database/schema.sql` mô tả DB mới. Cập nhật DB đang có phải chạy migration trong `src/db.ts`.',
    '- Dữ liệu demo được tạo bởi `src/seed.ts` và `src/seed-data.json`; không nhập `database/seed.sql`.',
    ''
  ].join('\n');

  const xml = value => String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
  const colors = ['#eff6ff', '#ecfdf5', '#fff7ed', '#fdf2f8'];
  const cells = ['<mxCell id="0"/>', '<mxCell id="1" parent="0"/>'];
  info.forEach((table, index) => {
    const col = index % 4;
    const row = Math.floor(index / 4);
    const label = `<b>${table.name}</b><br>${table.columns.map(c => `${c.pk ? '🔑 ' : ''}${c.name}${table.foreignKeys.some(f => f.from === c.name) ? ' → FK' : ''}`).join('<br>')}`;
    cells.push(`<mxCell id="tbl_${table.name}" value="${xml(label)}" style="rounded=1;whiteSpace=wrap;html=1;align=left;verticalAlign=top;spacing=9;fillColor=${colors[row % colors.length]};strokeColor=#475569;fontSize=11;" vertex="1" parent="1"><mxGeometry x="${col * 360 + 30}" y="${row * 310 + 30}" width="300" height="270" as="geometry"/></mxCell>`);
  });
  relationship.forEach((rel, index) => {
    cells.push(`<mxCell id="fk_${index}" value="${xml(rel.from)}" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;startArrow=${rel.cardinality === 'o|' ? 'ERone' : 'ERmany'};endArrow=ERone;strokeColor=#64748b;fontSize=10;" edge="1" parent="1" source="tbl_${rel.child}" target="tbl_${rel.parent}"><mxGeometry relative="1" as="geometry"/></mxCell>`);
  });
  const drawio = `<?xml version="1.0" encoding="UTF-8"?>\n<mxfile host="app.diagrams.net"><diagram name="MediBook SQLite"><mxGraphModel grid="1" gridSize="10" page="1" pageScale="1" pageWidth="1500" pageHeight="2300"><root>${cells.join('')}</root></mxGraphModel></diagram></mxfile>\n`;

  const outputs = [
    ['database/schema.sql', sql],
    ['docs/ERD.md', markdown],
    ['docs/MediBook_ERD.drawio', drawio],
    ['database/seed.sql', '-- Demo data is managed by src/seed.ts and src/seed-data.json.\n']
  ];
  const check = process.argv.includes('--check');
  const outdated = outputs.filter(([file, content]) => !fs.existsSync(path.join(root, file)) || fs.readFileSync(path.join(root, file), 'utf8').replace(/\r\n/g, '\n') !== content);
  if (check && outdated.length) {
    console.error('Schema documentation is out of date:', outdated.map(([file]) => file).join(', '));
    process.exitCode = 1;
  } else if (!check) {
    outputs.forEach(([file, content]) => fs.writeFileSync(path.join(root, file), content, 'utf8'));
  }
  console.log(`${tables.length} tables, ${relationship.length} foreign keys; ${check ? 'checked' : 'synchronized'} ERD and SQLite schema`);
} finally {
  if (db) db.close();
  for (const suffix of ['', '-wal', '-shm', '-journal']) {
    try { fs.unlinkSync(dbPath + suffix); } catch (_) { /* SQLite file may not exist */ }
  }
}
